"""GraphRAG community layer.

AuraDB Free does not include the GDS library, so community detection runs
offline with NetworkX (greedy modularity) over the Concept subgraph. We write
``Community`` nodes + ``CONTAINS`` edges back into the graph; the natural-language
community summaries are generated by the agent (see prompts/community_summary.md)
and can be attached afterwards via ``set_community_summary``.
"""
from __future__ import annotations

from .model import (
    COMMONLY_CONFUSED_WITH, COMMUNITY, CONCEPT, CONTAINS, PREREQUISITE_OF,
    RELATED_TO, KnowledgeGraph, make_uid,
)

CONCEPT_EDGE_TYPES = {RELATED_TO, PREREQUISITE_OF, COMMONLY_CONFUSED_WITH}


def _concept_subgraph(kg: KnowledgeGraph):
    import networkx as nx

    g = nx.Graph()
    concept_uids = {n.uid for n in kg.nodes_with_label(CONCEPT)}
    g.add_nodes_from(concept_uids)
    for e in kg.edges.values():
        if e.rel in CONCEPT_EDGE_TYPES and e.src in concept_uids and e.dst in concept_uids:
            g.add_edge(e.src, e.dst)
    return g


def detect_communities(kg: KnowledgeGraph, min_size: int = 2) -> int:
    """Detect concept communities and add Community nodes. Returns the count."""
    import networkx as nx
    from networkx.algorithms.community import greedy_modularity_communities

    g = _concept_subgraph(kg)
    if g.number_of_edges() == 0:
        return 0
    communities = greedy_modularity_communities(g)
    created = 0
    for i, members in enumerate(communities):
        members = list(members)
        if len(members) < min_size:
            continue
        names = [kg.nodes[m].props.get("name", m) for m in members]
        label = ", ".join(sorted(names)[:5])
        cuid = kg.add_node(
            COMMUNITY, make_uid(COMMUNITY, str(i), label),
            name=f"Community {i}", member_names=names, size=len(members),
            # summary attached later by the agent
        )
        for m in members:
            kg.add_edge(cuid, CONTAINS, m)
        created += 1
    return created


def set_community_summary(kg: KnowledgeGraph, community_uid: str, summary: str) -> None:
    if community_uid in kg.nodes:
        kg.nodes[community_uid].props["summary"] = summary
